### PR TITLE
Fix: golangci-lint warnings

### PR DESCRIPTION
**Pull request by ctlong**

### CODE REVIEW

**Comment by ctlong** [comment]
Made an issue to track logging the `envstruct.Write` errors: https://github.com/cloudfoundry/loggregator-agent-release/issues/111.

**Comment by ctlong** [comment]
LGTM! I can't approve the PR since I was the one who initially made it though.

@rroberts2222 @duanemay want to approve it?

**Review by duanemay — APPROVED** [review]
LGTM

**Review by Benjamintf1 — APPROVED** [review]
.

**Pull request merged**
