### PR TITLE
Feat: standardize logging

### PR DESCRIPTION
**Pull request by ctlong**
# Description

Standardize logging across agents.

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [x] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

### CODE REVIEW

**Comment by chombium** [comment]
Hi @ctlong,

I really like the idea of standardizing the logging, I have three questions though:
1. Why not using some logging library? Do you think that we need our custom solution, because we have some special logging needs?
2. What's the meaning of a session? Can you give some examples how it should be used?
3. I was expecting to see a log level: `ERROR`, `INFO`, `DEBUG` etc. as well and based on the level, the appropriate messages to be written to the log. Do you plan to add log level as well?

This looks like a wip to me, so I want to know what are the ideas how it should work ;)

**Comment by ctlong** [comment]
@chombium this is definitely a WIP 😅. I left it in draft format for that reason, but also didn't expect anyone to look at it so quickly.

As to your questions:

1. I'm happy to use a logging library instead. I started this way partly because I was curious to see if this was easy without a logging library, and partly because it was hard to choose a logging library out of everything available.
2. In my head starting a session represents entering some area of the code, and adding a new prefix to the existing prefixes to represent that. (i.e. after `logr := logr.Session("egress")`, `logr.Infof("my log line")` will output `<timestamp> INFO egress: my log line`)
3. This code already includes log levels, check out the individual methods. (i.e. `Infof`, `Errorf`)

**Comment by chombium** [comment]
Thanks for the clarification @ctlong. Thb I'm also not sure if we need some logging library...

When I've written about log levels, I meant that the user sets a log level and it doesn't get the log messages which are with lower priority than this level. A parameter with which the "log chattiness" of the app can be controlled.
For example:
- ERROR: prints only errors
- WARNING: prints errors and warnings
- INFO: prints errors, warnings and info messages
- DEBUG: prints everything

**Comment by ctlong** [comment]
> When I've written about log levels, I meant that the user sets a log level and it doesn't get the log messages which are with lower priority than this level. A parameter with which the "log chattiness" of the app can be controlled.
For example:
> 
> ERROR: prints only errors
WARNING: prints errors and warnings
INFO: prints errors, warnings and info messages
DEBUG: prints everything

Thanks for clarifying! Yeah, I agree that makes sense compared to using conditionals throughout code to check whether to run an `log.Infof` or whatever 😄.

**Comment by ctlong** [comment]
Just amended the commit to include log levels.

**Comment by ctlong** [comment]
Now planning to wait until [structured logging comes to the Go standard library (expected in Go 1.21)](https://github.com/golang/go/issues/56345).

**Pull request closed without merging**
