### PR TITLE
Add optional mutual TLS for internal syslog drains

### PR DESCRIPTION
**Pull request by chombium**
# Description

Activates mutual TLS  for the internal drains in the syslog agents. All of the outgoing connections through internal syslog drains will be secured with mTLS, if the parameter to use mTLS for syslog drains is set to true. The goal is to harden the communication between the Syslog Agents running on all BOSH VMs and the Log-Cache Syslog Server and secure it with mutual TLS.

Changes:
- adjust BOSH job templates and add flag to activate mTLS for internal syslog drains like for example log-cache
- configure the syslog agent to use mTLS for internal syslog drains in case the DrainUseMTLS flag is true
- add test syslog  mTLS configuration to log-cache

Is there any documentation which should be updated? 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [X] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [X] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [X] I have added testing for my changes

### CODE REVIEW

**Comment by ctlong** [comment]
@chombium this is blocked on https://github.com/cloudfoundry/cloud_controller_ng/pull/2903 being merged, correct?

**Comment by chombium** [comment]
@ctlong this PR is not blocked by the cloud controller PR. 

The changes only touch the TLS configuration for the internal syslog drains (which means the aggregate drains from the syslog agent to log-cache). I thought that I can reuse the [loggregator_tls_agent](https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml#L2162-L2172) certificate from the cf-deployment for mTLS between the syslog agent and log-cache as is used in all other places for creating GRPC connections with mTLS between the Loggregator components. As the TLS cert-key pair are used for identification and are already present in the bpm config, I've added a new parameter with which the operators can explicitly activate mTLS for internal drains. Marking a syslog drain as internal is done by adding  `ssl-strict-internal=true` query parameter to the syslog drain url as used in the [cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml#L1359) and the internal TLS config is used when creating the writer [here](https://github.com/cloudfoundry/loggregator-agent-release/blob/main/src/pkg/egress/syslog/writer_factory.go#L43-L45).

As this configuration is for internal drains between syslog agent and log-cache I think that it should not be done via the binding-cache, but explicitly via envvars (deployment.yml configuration). As I've written earlier, for the mTLS I've reused the `loggregator_tls_agent` cert-key pair which is used for GRPC. If you think that hat's not the right certificate to use, we can discuss if we maybe need to introduce another cert.

**Comment by Benjamintf1** [comment]
@chombium My thought/hope, honestly, was to be able to refactor aggregate drains to take a query parameter with a named set of named certs configured in bosh? 

Maybe there's a future even betterer version of configuring things, but I can't think of anything more natural that doesn't require a lot of work right now either. 

Moreso, I also broadly suspect anyone who would want to setup a external tool like a elk stack would find the bosh certificates as client certificates of limited value, but also the ca certificate pool of limited value as well? I think there was a wish to avoid some hard-coded special purpose stuff for log-cache, and I think to a large degree it was achieved, however it was still a little too custom coded with the "ca_certificate" for trust, for example. I'd like to see log-cache just seen by syslog-agent as "just a configured drain" in the future even moreso. It ensures that options for syslog drains carry over well to non-internal syslog drains, but also I think is a little easier to reason about and less magical. 

Does that make sense?

**Comment by Benjamintf1** [comment]
(I was also expecting to see a pr like this *after* we finished up the individual mutual tls changes go through tbh)

**Comment by chombium** [comment]
Hi @Benjamintf1,

I'm glad that we are thinking in the right direction.

TBH. When I started working with Loggregator two years ago, it was more from the CF operator point of view, but when I did some problem triaging, I've stumbled upon the syslog agent and it was always bugging me why there are two TLS configs (internal and external) when every syslog drain should be treated equally. I thought that there is some special treatment for internal drains, but I was always wondering why, when the log-cache-syslog-server (then part of the Shared Nothing Loggregator Architecture) actually is yet another syslog drain.

I was trying to implement mTLS for the internal drains with as less changes as possible. As there is already implementation about optional activation of TLS, I've followed the same pattern. We also had doubts if we should reuse the same certificate as for GRPC or add more config parameters for a new one. As we were concentrated on internal drains and I saw that the certificate passed to the GRPC tls config is used everywhere in `cf-deployment` I've decided to reuse what's already existing.

I find the idea of waiting for the other PR for the external syslog drains to be merged and then refactoring and unifying the TLS configuration and handling really good.

We should definitely discuss the future of Loggregator and the direction in which the project goes more often. We've gained big knowledge in operating Loggregator int he past few years and we've have ideas for many possible improvement. Let's find a communication format how we can discuss all things Loggregator ;)

Now back to the PR, do you think its worth improving it and adding extra configuration parameters for the ca, cert and key which will be used for mTLS with internal syslog drains? Would that be a viable option until we do a proper refactoring or I should close the PR and we discuss the things further?

**Comment by Benjamintf1** [comment]
```
also had doubts if we should reuse the same certificate as for GRPC or add more config parameters for a new one.
```
I think my own inclination is to use a new one. You can always reuse the certificate if you wish, but ability to have seperate sets of certs i think is hypothetically a bit more secure and also better wrt configuration in general for drains.

```
Now back to the PR, do you think its worth improving it and adding extra configuration parameters for the ca, cert and key which will be used for mTLS with internal syslog drains? Would that be a viable option until we do a proper refactoring or I should close the PR and we discuss the things further?
```
I mean it's a bit rich for me to say to some degree given I'm not actually doing the work, but I think it'd be a good idea to at least have a configuration parameter in syslog-agent that allows setting certificates for use by aggregate drains, then you could just use the special aggregate only query params to refer to the map key?

**Comment by Benjamintf1** [comment]
So, just to reiterate some thoughts here.

My thought on how to do mtls for aggregate drains.

have a bosh setting, example config(aggregate_drain_certificates is the only one defined in the spec, all the rest dynamic?).

Ideally in terms of uptime we define it in the binding-cache, but it would be easier to define in the agent.

```
aggregate_drain_certificates:
    log_cache_certs:
       ca: |
          --begin cert--...
        cert: |
           -- begin cert--....
         key: |
           -- begin key--...
     elk_certs:
        ca: |
          --begin cert--...
        cert: |
           -- begin cert--....
         key: |
           -- begin key--...
```

then we can define aggregate drains with

```
<log-cache-address>?certs=log_cache_certs,<elk-address>?certs=elk_certs
```

Make a v2 binding-cache endpoint just like before but for aggregate which combines this information. This would allow us to have differing client identies and ca's for each aggregate drain(i suspect usually 1 log-cache and 1 other drain for external use). Then we can make sure log-cache can do mtls. Then we can make a pr for cf-d to update the bosh properties and bosh releases to use this new feature.

**Comment by chombium** [comment]
@Benjamintf1 I like your idea. So far I've drafted the PR for a single "internal" cert/key pair to log-cache.

I will rework this PR add everything to the binding cache and adapt it to cover all aggregate drains.

**Comment by Benjamintf1** [comment]
`Do you think we need to support multiple cert-key pairs on the log-cache side as well?`

No, honestly, I think it should be fine. Sorry I forgot about the log-cache side/havn't processed it at all. I'll try and find some time to look into/process it sometime soon. I either might not have realized that pr existed, or falsely gated it on the loggregator-agent work.

**Comment by chombium** [comment]
I've closed this PR in favor of #187. We can continue the discussion there.

**Pull request closed without merging**
