### PR TITLE
[WIP] Add optional mutual TLS for aggregate drains

### PR DESCRIPTION
**Pull request by chombium**
# Description

Please include a summary of the change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [ ] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

### CODE REVIEW

**Comment by chombium** [comment]
@Benjamintf1 we had a chat with @fhambrec and decided that it would be better to use the following configuration structure as it would be better to fit it in the new [Binding](https://github.com/cloudfoundry/loggregator-agent-release/blob/main/src/pkg/binding/poller.go#L40-L43) struct:

```
aggregate_drain_certificates:
  - url: url1
     ca: |
      --begin cert--...
    cert: |
       -- begin cert--....
     key: |
       -- begin key--...
  - url: url2
     ca: |
      --begin cert--...
    cert: |
       -- begin cert--....
     key: |
       -- begin key--...
```

The definition of the aggregate drains will stay as is at the moment:
```
url1,url2
```

Activating mTLS will be optional. If the url in the `aggregate_drains` definition matches the url of an object in the `aggregate_drain_certificates` than mTLS config will be sent to the syslog agent which will activate mTLS with the given configuration.

What do you think about this?

**Comment by Benjamintf1** [comment]
(yamlizing the old aggregate drain config and new map together in the templating step might be the easiest way to merge the properties?)

**Comment by chombium** [comment]
@Benjamintf1 I agree with you that having both properties feels awkward. IMO keeping the old config backward compatible and doing some template merging would be even worse. 

I personally would make breaking changes and extend the `aggregate_drains` as an array of objects together with the certs. I don't think that at the moment someone uses the aggregate drains extensively, except as we used them for Log Cache ...

@fhambrec, @ctlong Any thoughts on this?

**Comment by Benjamintf1** [comment]
I'm aware of people using aggregate drains, but it's not used as extensively as nozzles. Ideally, I'd like to see people move over to them though.

**Comment by chombium** [comment]
What if we say that the value of the `aggregate_drains` property can be either string or array of objects? The only overhead would be that the value has to be unmarshalled manually. There might be more manual work for validating and parsing the value, but it will be backward compatible.

**Comment by Benjamintf1** [comment]
That's possible? Sorry for the very late response, but that sounds nice to me.

**Comment by chombium** [comment]
@Benjamintf1 I'm sorry for the late response too :) We've discussed this with @fhambrec how can we implement this with the new mtls structs, I've started to implement something, so that we have some code to discuss on, but due to some other more urgent things I was not able to bring it to some possibly usable state. I'll try to finish the initial changes this week, so that we can continue the discussion.

**Comment by Benjamintf1** [comment]
I assume you got busy? I'm working on something here that should handle things. https://github.com/cloudfoundry/loggregator-agent-release/tree/ben-aggregate-drain-mtls

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/pull/276 made it in pr form here.

**Comment by Benjamintf1** [comment]
Can't get it to work at the moment and I'm not entirely sure why.... binding-cache seems to be fine, and seems to be reporting swimingly, but I can't get it to actually send logs to log-cache.

**Comment by chombium** [comment]
Yup, unfortunately I got too busy with other stuff :( I'll take a look at your PR and we can sync on how should we proceed. If you already have a working solution, I guess we can close this PR

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/pull/276 done I believe.

**Pull request closed without merging**
